### ISSUE TITLE
🐛 : ios Build error : The 'jsc/JSCRuntime.h' was not found 

### ISSUE THREAD

**Issue by mmlee0819** [margelo/react-native-worklets-core#115]
### What's happening?

I'm trying to use the Frame Processors feature of react-native-vision-camera, so I installed react-native-worklets-core following the troubleshooting steps mentioned [here](https://www.react-native-vision-camera.com/docs/guides/troubleshooting).

Platform iOS in Podfile is 13.0 and Swift version is 5.2.

When I only had react-native-vision-camera installed, everything worked fine. However, after installing react-native-worklets-core, I encountered the following issue:

WKTJsRuntimeFactory.h:15:10 'jsc/JSCRuntime.h' file not found

I've reviewed the troubleshooting guide, but found none.
I would greatly appreciate any guidance or relevant resources to help me resolve this issue.

### Reproduceable Code
No response

### Relevant log output
ios:
/Users/xxxx/xxxxxxx/xxxxxxx/node_modules/react-native-worklets-core/cpp/WKTJsRuntimeFactory.h:15:10 'jsc/JSCRuntime.h' file not found

![image](https://github.com/margelo/react-native-worklets-core/assets/102346844/71559b14-df57-407a-a2ad-cc851a40c366)

### Camera Device
No response

### Device
iOS 16.6.1
Xcode 14.3.1

### VisionCamera Version
3.0.0

### Package Versions
"react": "18.2.0"
"react-native": "0.71.6"
"react-native-reanimated": "2.17.0", unable to upgrade to 3.2.0 or higher for some reason.
"react-native-vision-camera": "^3.0.0" /  "2.15.4" / "2.15.6" , tried 3 versions
"react-native-worklets-core": "^0.2.0"

### Can you reproduce this issue in the VisionCamera Example app?
- [ ]  I can reproduce the issue in the VisionCamera Example app.

Additional information
- [ ]  I am using Expo
- [x]  I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [x]  I searched for similar issues in repository [react-native-vision-camera](https://github.com/mrousavy/react-native-vision-camera/issues) and [react-native-worklets-core](https://github.com/margelo/react-native-worklets-core/issues) and found none.

**Comment by vadbertalan** [comment]
Submitted PR (https://github.com/margelo/react-native-worklets-core/pull/118) with the possible fix.

**Comment by mmjc29** [comment]
Same problem

But I don't want to udpate the react-native 0.72.4

I am still on 0.70

Is it neccessary to update ?

**Comment by PauloGrachetelli** [comment]
> Same problem
> 
> But I don't want to udpate the react-native 0.72.4
> 
> I am still on 0.70
> 
> Is it neccessary to update ?

if you want publish apps at android 33 API you must update RN version =(

**Comment by josh-thompson13** [comment]
Same problem guys. 

I tried to "<react-jsc/JSCRuntime.h>" fix mentioned above and just got the same error.


Packages:
"react-native-vision-camera": "3.2.2",
"react-native-worklets-core": "0.2.2",

**Comment by PauloGrachetelli** [comment]
if you need this package for qr scanner, just use latest version of vision camera

**Comment by josh-thompson13** [comment]
@PauloGrachetelli So I removed worklets core and now I can build on IOS... but can no longer build on web. Getting the following error when building with metro:

`error: Error: Unable to resolve module react-native-worklets-core from /Users/joshthompson/trinoor/tas-v/node_modules/react-native-vision-camera/lib/commonjs/FrameProcessorPlugins.js: react-native-worklets-core could not be found within the project or in these directories:
  node_modules/react-native-vision-camera/node_modules
  node_modules
  15 | };
  16 | let runOnAsyncContext = (_frame, _func) => {
> 17 |   throw new _CameraError.CameraRuntimeError('system/frame-processors-unavailable', 'Frame Processors are not available, react-native-worklets-core is not installed!');
     |                                                                                                                         ^
  18 | };
  19 | try {
  20 |   (0, _JSIHelper.assertJSIAvailable)();
    at ModuleResolver.resolveDependency (/Users/joshthompson/trinoor/tas-v/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:15)
    at DependencyGraph.resolveDependency (/Users/joshthompson/trinoor/tas-v/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/Users/joshthompson/trinoor/tas-v/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/joshthompson/trinoor/tas-v/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/joshthompson/trinoor/tas-v/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/joshthompson/trinoor/tas-v/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/joshthompson/trinoor/tas-v/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async addDependency (/Users/joshthompson/trinoor/tas-v/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 5)
 MAP  ./index.js `

**Comment by PauloGrachetelli** [comment]
"react-native-worklets-core": "^0.2.0",
"react-native-vision-camera": "3.3.1",
https://www.react-native-vision-camera.com/docs/guides/code-scanning

Try this, a month ago everyone had a similar error, it was fixed in this version

**Comment by francesco-clementi-92** [comment]
I have also the same problem with the following packages:
```
"react-native": "0.71.14",
"react-native-vision-camera": "^3.6.4",
"react-native-worklets-core": "^0.2.4",
```
switching to `#include <react-jsc/JSCRuntime.h>` doesn't fix the problem

**Comment by rafaelmotta** [comment]
same here. From my understanding, this is because Hermes is required. would be great if we could use JSC too

**Comment by LongNguyen2312** [comment]
Is there a solution for this problem yet?

**Comment by oguzydz** [comment]
any update on this?
