### ISSUE TITLE
Is there a way to make an HTTP request in a worklet?

### ISSUE THREAD

**Issue by findhumane** [margelo/react-native-worklets-core#145]
I want to download a file from a remote server in a worklet and then cache it in my main JS app. I don't want to do this in my main JS app because it would pause the JS thread unnecessarily. I got a basic "Hello World" worklet working on Android with an Expo SDK 50 project.

I understand worklets [don't support async/await](https://github.com/margelo/react-native-worklets-core/issues/109) and packages like `fetch` [aren't worklets](https://github.com/margelo/react-native-worklets-core/issues/116), but I thought I could use [`XMLHttpRequest` in synchronous mode](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API/Synchronous_and_Asynchronous_Requests#synchronous_request); however, I get the error, `TypeError: This function cannot be used as a constructor.`, presumably when calling `new XMLHttpRequest`. Passing in the `XMLHttpRequest` doesn't work either.

Is this possible with `react-native-worklets-core`? If not, is there an alternative? Thanks!

Code snippets:

```js
import * as React from 'react';
import { Worklets } from 'react-native-worklets-core';

function asyncWorkletDownloadFile(url) {
  "worklet";

  try {
    const xhr = new XMLHttpRequest();

    // `false` makes the request synchronous
    xhr.open(
      "GET",
      url,
      false
    );

    // `null` means no body since it's a GET
    xhr.send(null);
    if (xhr.status === 200) {
      return xhr.responseText;
    } else {
      return "ERROR: Status: " + xhr.status;
    }
  } catch (e) {
    return "ERROR: " + e.toString();
  }
}

function asyncWorkletDownloadFileResult(result) {
  console.log("worklet responded: " + result);
}

export function MyApp() {
  React.useEffect(() => {
    const worklet = Worklets.createRunInContextFn(asyncWorkletDownloadFile);
    worklet("https://example.com/").then(asyncWorkletDownloadFileResult);
  }, []);
});
```

**Comment by findhumane** [comment]
Resolved with a custom native module: https://github.com/findhumane/react-native-threaded-downloader

**Comment by chrfalch** [comment]
Nice, will close this issue.

**Comment by pleerock** [comment]
@findhumane author basically didn't use `react-native-worklets-core` in this solution. So, original issue persists. Is it technically possible to make threads to support asynchronous code execution? Because there are many, many cases when you just want to run on a separate thread peace of code which does IO operations (http queries, calls to the database, etc.).
