### ISSUE TITLE
#import "RNWorkletsSpec.h" not found when new Arch enabled

### ISSUE THREAD

**Issue by primesay** [margelo/react-native-worklets-core#213]
Env: 

-  "react-native": "0.75.2",
- "react-native-vision-camera": "4.5.1",
- "react-native-worklets-core": "1.3.3",
-  "react": "18.3.1",

On IOS = 13.4

when i try to build i got this errror :
     'RNWorkletsSpec.h' file not found

<img width="854" alt="image" src="https://github.com/user-attachments/assets/5c955c1b-1ce5-4fa5-b26e-e3c967249338">

any help ? patches ?

**Comment by primesay** [comment]
this issue is resolved by adding this lines to to the PodFile
```
installer.pods_project.targets.each do |target|
          if target.name == 'RNWorklets'
            target.build_configurations.each do |config|
              # Add compiler flags
              config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)', '-DRCT_NEW_ARCH_ENABLED=1']
              
              # Add header search paths
              config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)', '"$(PODS_ROOT)/boost"']

              # Add other flags for C++
              config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= [
                '$(inherited)',
                '-DFOLLY_NO_CONFIG',
                '-DFOLLY_MOBILE=1',
                '-DFOLLY_USE_LIBCPP=1'
              ]
              
              # Set C++ language standard
              config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
          end
   end
    end
```

**Comment by hannojg** [comment]
This should be automatically fixed with the latest version (1.5.0 as of writing)

**Comment by scott-harrison** [comment]
Tried updating to 1.5.0, still getting the same problem. I have tried the podfile changes. No change still get 'RNWorkletsSpec.h' file not found

**Comment by marf** [comment]
Same issue here, any ideas on how to fix it? I have the 1.5.0 version

**Comment by scott-harrison** [comment]
> Same issue here, any ideas on how to fix it? I have the 1.5.0 version

I did fix this issue for my project, but forgotten the exact steps I used. But the solution for me was to run the codegen command. when you run codegen it generates the spec file.

**Comment by marf** [comment]
>  I did fix this issue for my project, but forgotten the exact steps I used. But the solution for me was to run the codegen command. when you run codegen it generates the spec file.

Thank you, I will try that. Do you remember the command you used to run codegen?

**Comment by scott-harrison** [comment]
`npx react-native codegen`

**Comment by marf** [comment]
> npx react-native codegen

Thank you very much!

**Comment by MuhammadTalhaTahir1** [comment]
I am still getting the same RNWorkletsSpec.h file not found error.
I tried changing the Podfile and also running react-native codegen, but it didn’t solve the problem.

react-native: 0.77.3
react-native-worklets-core: ^1.3.3
react-native-vision-camera: 4.7.0
react: 18.3.1

Xcode version= 16.3
